# Generated by Django 5.0.4 on 2024-05-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='profilePhotos'),
        ),
    ]
