# Generated by Django 5.0.4 on 2024-05-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_person_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profilePhotos'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='coverPhotos'),
        ),
    ]
