# Generated by Django 5.0.4 on 2024-05-25 19:31

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_person_profile_photo_alter_person_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=Users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=Users.models.user_directory_path),
        ),
    ]
